services:
  postgres:
    image: postgres:17
    container_name: chatsystem-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:5
    container_name: chatsystem-cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_DC: ${CASSANDRA_LOCAL_DATACENTER}
      CASSANDRA_RACK: ${CASSANDRA_RACK}
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis
    container_name: chatsystem-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  cassandra_data: